### ISSUE TITLE
介意把zh_tw版默認的陸標字體（如Noto Serif SC）換成台標嗎？

### ISSUE THREAD

**Issue by QChWnd** [Fuukei/Sakurairo-zh_tw#8]
> 注意，在报告之前请先确认：**这个想法能被多数人接受；这个想法会让这个主题更好。**
> 当你确定你的想法满足以上条件之后，请删除这段文本并继续。

**这是什么方面的想法？**
用户体验

**这个想法具体是要实现什么？**
如題

**这个想法实现后有什么帮助？**
本地化

**是否有具体的实现思路？**
（換掉即可）

**补充信息：**

**Comment by mirai-mamori** [comment]
在下一次更新中，zh-TW版將併入主線版本。屆時將為zh-TW版本推送更新，以幫助使用者遷移到主線版本。主線版本將提供多語言支持，因此暫不考慮將默認字體更換為台標。如果你願意參與zh-TW版本的本地化工作，請聯繫我，謝謝。
